### ISSUE TITLE
NPE: at it.eng.stamp.results.DescartesReport.doIndex(DescartesReport.java:159)

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/stamp-ci#13]
**STAMP Tools Reports Publisher** doesn't work to visualize the Descartes report, either with: 

- default Custom search path, set to `**/target/pit-reports/*/mutations.json`
- or which specified one, set to: `**/target/pit-reports/201903261627/mutations.json`
However, Descartes report exists in Jenkins job workspace in route:
```
[root@supersede eu.supersede.if.api]# ls target/pit-reports/201903261627/
issues  methods.json  mutations.json
```
When Jenkins job is executed, I get the following NPE in console:
```
ERROR: Build step failed with exception
java.lang.NullPointerException
	at it.eng.stamp.results.DescartesReport.doIndex(DescartesReport.java:159)
	at it.eng.stamp.STAMPReportCollector.perform(STAMPReportCollector.java:114)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'STAMP Tools Reports Publisher' marked build as failure
```
Another issue, how can I specify all Descartes files in a report, including mutation.json and methods.json? Using `**/target/pit-reports/*/*.json`?

**Comment by pasquy73** [comment]
I've updated the [descartes-jenkins-plugin](https://github.com/STAMP-project/stamp-jenkins/tree/master/descartes-jenkins-plugin) to 1.0.0 version. You can download it and try with mvn package or you can use directly this [stamp-report-plugin.zip](https://github.com/STAMP-project/stamp-jenkins/files/3085503/stamp-report-plugin.zip).

**Comment by jesus-gorronogoitia** [comment]
Ciao @pasquy73 
Grazie mille. I've installed the new version of this Descartes Jenkins plugin you fixed, and it is working fine.
So, I close this issue. I will use your plugin to analyze Descartes reports on Atos Supersede IF component.
